name: Tag Release Workflow

on:
  push:
    tags:
      - 'v*'  # Match tags that start with 'v' (e.g., v1.0.0)

jobs:
  create_tag_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a new branch from the tag
      run: |
        TAG_NAME="${GITHUB_REF/refs\/tags\//}"
        NEW_BRANCH_NAME="release/${TAG_NAME}"
        git checkout -b "${NEW_BRANCH_NAME}"
        git push origin "${NEW_BRANCH_NAME}"

    - name: Create a PR to master
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{ steps.create_tag_release.outputs.TAG_NAME }}
        title: "Release ${{ steps.create_tag_release.outputs.TAG_NAME }}"
        body: "This PR is created automatically to release version ${{ steps.create_tag_release.outputs.TAG_NAME }}"
        labels: "automated-pr"