name: Tag Release Workflow

on:
  push:
    tags:
      - 'v*'  # Match tags that start with 'v' (e.g., v1.0.0)

jobs:
  create_tag_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a new branch from the tag
      run: |
        TAG_NAME="${GITHUB_REF/refs\/tags\//}"
        NEW_BRANCH_NAME="release/${TAG_NAME}"
        git checkout -b "${NEW_BRANCH_NAME}"
        git push origin "${NEW_BRANCH_NAME}"

    - name: Create a PR to master
      run: |
        TAG_NAME="${GITHUB_REF/refs\/tags\//}"
        NEW_BRANCH_NAME="release/${TAG_NAME}"
        gh pr create --base master --head "${NEW_BRANCH_NAME}" --title "Release ${TAG_NAME}" --body "This PR is created automatically to release version ${TAG_NAME}" --label "automated-pr"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}